# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusConductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('wallet', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=200)),
                ('otpcode', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('wallet', models.FloatField(default=0.0)),
            ],
        ),
    ]
