# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField()),
                ('busname', models.CharField(max_length=200)),
                ('startid', models.IntegerField()),
                ('endid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveConductorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('busname', models.CharField(max_length=200)),
                ('busnumber', models.CharField(max_length=20)),
            ],
        ),
    ]
