# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0003_auto_20171228_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveconductordetails',
            old_name='cusername',
            new_name='username',
        ),
    ]
