# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-29 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0004_auto_20171228_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
