# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-29 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0005_busstations'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstations',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
