# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-29 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0006_busstations_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField()),
                ('station_id', models.IntegerField()),
                ('sequence', models.IntegerField()),
            ],
        ),
    ]
