# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-29 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0007_routesequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBusDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusername', models.CharField(max_length=200)),
                ('busname', models.CharField(max_length=200)),
                ('busnumber', models.CharField(max_length=20)),
                ('currstation', models.CharField(max_length=200)),
                ('whichway', models.CharField(max_length=200)),
                ('tripno', models.IntegerField()),
            ],
        ),
    ]
