# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-30 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0008_livebusdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusername', models.CharField(max_length=200)),
                ('busname', models.CharField(max_length=200)),
                ('busnumber', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('sourcestation', models.CharField(max_length=200)),
                ('deststation', models.CharField(max_length=200)),
                ('totalfare', models.FloatField()),
                ('qrcode', models.CharField(max_length=200)),
            ],
        ),
    ]
