# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-30 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0009_tickettransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busconductor',
            name='wallet',
            field=models.FloatField(default=2000.0),
        ),
    ]
