# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-31 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0010_auto_20171230_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationsOnRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('route_id', models.IntegerField()),
            ],
        ),
    ]
