# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0011_stationsonroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettransactions',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
