# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0012_auto_20180102_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTransactionsCond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusername', models.CharField(max_length=200)),
                ('busname', models.CharField(max_length=200)),
                ('busnumber', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('sourcestation', models.CharField(max_length=200)),
                ('deststation', models.CharField(max_length=200)),
                ('totalfare', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketTransactionsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=200)),
                ('cusername', models.CharField(max_length=200)),
                ('busname', models.CharField(max_length=200)),
                ('busnumber', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('sourcestation', models.CharField(max_length=200)),
                ('deststation', models.CharField(max_length=200)),
                ('totalfare', models.FloatField()),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode')),
                ('datetime', models.DateTimeField(blank=True, default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='TicketTransactions',
        ),
    ]
