# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jctslapi', '0014_auto_20180102_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettransactionsuser',
            name='tripno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
